### ISSUE TITLE
CO15 Isolation and Elimination

### ISSUE THREAD

**Issue by Invaderok** [TacticalShift/mmo#16]
#### Миссия:
[- Ссылка_на_файл_архива_миссии](https://github.com/TacticalShift/mmo/blob/main/CO15_Isolation_and_Elimination.Tanoa.7z)

#### Описание 
Search bloc vs Medellin cartel

**Comment by Reneval228** [comment]
В брифинге в поддержке указано вертолет UH-1Y, а на самом деле у нас UH-1H
1. Убрать у главы картеля пулемет.
2. Переименовать киты для машин и т.д (добавить cargo)
3. Мало медикаментов в лодок и в вертолете.
4. Добавить боевые гранаты для пилота.
5. Добавить дымовые гранаты для босса картеля.
6. Добавить патрон в лодках побольше.
7. Я бы разместил вертолет на вертолетной площадки у FARP'а, но это на твое усмотрение.
8. Слишком скучно в доме, я бы добавил какие-то цвет в коридоре чтоб красиво было.
9. Если машины бесполезны, то заблокировать их.
10. Platoon Sergeant не может являться пилотом, т.к он ГСО, добавить слот для пилота.

**Comment by Invaderok** [comment]
0. Вертолет переименовал.
1. Пулемет забирать не буду, так задумано. Какая причина чтобы его забрать то? Захотел он как ремба дома пострелять. (https://youtu.be/9m_12SGXNKw?t=67)
2. Машины не играбельные на этой карте (по задумке вы до берега на них приехали), я их просто заблокирую и все.
3. Надувные лодки в принципе мало везут веса с учетом еще 5 человек и уже имеющегося БК там. Если нужны доп медикаменты, просите гсо привезти на вертолете. У нас люди быстрее умирают чем свой собственный запас медикаментов тратят.
![image](https://github.com/TacticalShift/mmo/assets/168902359/c20de871-d115-4ef4-9ce9-b4a4012d0252)
4. Зачем пилоту боевые гранаты? С вертолета их кидать? На крайний случай возьмет из вертолета, там 10 гранат.
5. А зачем босу картеля гранаты дымовые? Его задача забаррикадироваться в доме и сдохнуть или типо убежать просто (по истории если не взорвут лодки). Он в костюме и бронике без карманов.
7. См. пункт 3. Добавил чуть (по 5) еще медикаментов в лодку большую и верт.
8. Я боюсь что фарп там может вертолет поломать если фарп заспавнится не так как обычно. По этому поставил его на дороге где есть место нормально чтобы взлететь.
9. Добавил энвиропмента. Там впринципе одни коридоры, по мелочи накидал.
10. На берегу заблокировал, у картелевских оставил, вдруг игроки захотят уехать на них к берегу.
11.  Задача платун сержанта просто где то в небе зависнуть чтобы ПЛ мог руководить ситуацией сверху, при автозависании можешь летать делать свои делишки в зевсе. Вертолет сугубо разведывательная машина типо дрона. Учитывая это, у сержанта, имхо будет время если что слетать за патронами и тд. Либо вообще можно вертолет не трогать, он опционален в миссии. Если ты не согласен, можно в гсо чат вынести этот вопрос и обсудить.
![image](https://github.com/TacticalShift/mmo/assets/168902359/df34736e-1af8-4955-8720-7743f83307ee)

**Comment by Reneval228** [comment]
Хорошо, я пока ничего не нашел, так что может еще комрад или кабан посмотрит, а так отлично))

**Comment by Invaderok** [comment]
Добавил слот пилота за счет одного из резервных слотов. 
Пилот в подчинении 1.6, так как это вертолет командования для координации.

**Comment by OneScheer** [comment]
Даю добро
