### ISSUE TITLE
CO23 Operations The Borezhsky Uprising

### ISSUE THREAD

**Issue by Home1234Home** [TacticalShift/mmo#28]
#### Миссия:
https://github.com/TacticalShift/mmo/blob/main/CO23_Operations_The_Borezhsky_Uprising.VTF_Korsac.zip

#### Описание 
Вооружённые силы Приднестровской Молдавской Республики захватывают укрепления повстанцев

**Comment by Home1234Home** [comment]
https://github.com/TacticalShift/mmo/blob/main/CO23_Operations_The_Borezhsky_Uprising.VTF_Korsac.zip
Обновлена техника с Т-72 НА Т64БВ
Изменён пункт поддержка в брифинге (указано выше)
Изменён пункт обстановка в брифинге

**Comment by Arsdor** [comment]
1) В description почему-то стоит только время. В целом сложно понять, о чём миссия.
2) В брифинге много ошибок: 
а) Должно быть Пр**и**днестровье
б) заятая после слова "повстанцев"
в) НАТО не выделяется кавычками
г) запятая после слова "известно"
д) выбить противник**а**
И другие
3) На карте почти отсутствуют маркеры
4) ошибки китов "There is no kit name"
5) У пулемётчика РПК-74, в рюкзаке патроны к РПК. У стрелка, соответственно, тоже патроны к РПК калибра 7,62
6) Объекты не оптимизированы
7) Вообще не понятно, кто, против кого, и, наконец, зачем.

**Comment by Comrade333** [comment]
Открывал только текстовую версию.
Помимо ошибок от Арсдора.

1) В враждебных силах указывается, что за противник против нас, ориентировочная численность, позиции противника на которые стоит обратить внимания и какие средства у него есть.
Строчки по типу "Нам необходимо/мы должны" прописываются в пункте выполнении.

2) Дружественная сторона также непонятно кто, что и почему.
Примеры описания
![image](https://github.com/user-attachments/assets/1358e298-94d8-4a40-ada0-58a1d82deded)
![image](https://github.com/user-attachments/assets/757bb760-c378-4744-a04e-03f4700437fd)
![image](https://github.com/user-attachments/assets/41714166-1953-4c51-9961-08141dccacfa)

3) Указать про наличие CCP и FARP в поддержке.

4) В description нет краткого описания миссии

5) Заполнить Introtext

6) Сейчас будет духота, но
Обычно отсыплют оружие попроще с которым в этом регионе плюс минус пользоваться умеют, прошу постараться задефайнить разных калашей постарше и парочку аройдов,.
А то сейчас еба оптики и винтовки ценой по 2-5 к баксов, выглядит они как повстанцы с одного острова в 2035, очень пахнет ctrl+c ctrl+v на ванильных китах.

**Comment by Home1234Home** [comment]
https://github.com/TacticalShift/mmo/blob/main/CO23_Operations_The_Borezhsky_Uprising.VTF_Korsac.zip
description исправлено 
Брифинг исправлен
Маркеры добавлены
There is no kit name исправлено
магазины к рпк исправлены
Объекты оптимизированы

**Comment by OneScheer** [comment]
- Ванильные киты на врагах
- ![Боты с Loiter?](https://github.com/user-attachments/assets/3e86c46d-d0bc-4b6e-89e0-e435cfeb5a31)
Вейпоинт Loiter нужен для летающей техники. К тому же зачем в целом ставить ботов если есть дунай. 
Основная претензия:
Это один в один миссия арсдора Alga. Вплоть до зоны операции, расположения союзных и вражеских сил. 
![20240719093056_1](https://github.com/user-attachments/assets/2db917ea-6d34-4ae9-a47e-95463fb46071)
