### ISSUE TITLE
CO20 Nasha Posadka

### ISSUE THREAD

**Issue by OneScheer** [TacticalShift/mmo#31]
#### Миссия:
- [Ссылка_на_файл_архива_миссии](https://github.com/TacticalShift/mmo/blob/main/CO20_Nasha_Posadka_1A.cup_chernarus_A3.zip)

#### Описание 
Добровольцы НАПА занимают важные позиции в лесополосе около н.п. Пустошка

**Comment by Invaderok** [comment]
1) Брифинг. "Буря" тоже нужно в кавычки же? Название операции.
2) Брифинг. Снаряжение, а также бронетехника, для штурма и транспортировки, были...
3) Враждебные силы. Днем ранее, в районе операции, были замечены БМП, а также развертывание дополнительной минометной батареи, в районе населенного пункта.
4) Отсутствует ящик со снаряжением на базе, он точнее есть с минометом, но помимо больше ничего нет.
5) Магазины 5.45 от калаша отличаются от китовых (у тех кому 74м дают), то есть нужно будет выбирать что заряжать, я бы сделал у всех одинаковые, это не критично, но игрокам будет удобнее. У одних черные у вторых коричневые.
6) В снаряжении БТР отсутствуют снаряды для ПТ.
7) *Опционально* Для ААТ я бы дал тоже сумку рпг и не по 1 снаряду, а по 2.
8) *Опционально* Я бы зарандомил ГПшеру так же АК с ГП, раз у нас тут помесь калычей и м-очек, правда нужно гп будет еще в киты транспорта от калаша засунуть.
9) *Опционально* У rAT + MG бота нет гранат, все же каефно откисать от гранат ботов :3

**Comment by OneScheer** [comment]
1. Исправил
2. Исправил
3. Исправил, забыл руську мову
4. Добавил пару ящиков, хотя снаряжение есть плюсом в машинках и на FARP
5. Там два калаша, АК-74 и АК-74М, к первому бакелитовые магазины, ко второму черные
6. Добавил
7. Добавил два ПТ гранаты
8. заебно, мне лень)
9. Добавил ПТшнику

**Comment by Invaderok** [comment]
Одобрено.
