### ISSUE TITLE
CO22 Farabad Blues Part One Bridge

### ISSUE THREAD

**Issue by OneScheer** [TacticalShift/mmo#34]
#### Миссия:
[- Ссылка_на_файл_архива_миссии](https://github.com/TacticalShift/mmo/blob/main/CO22_Farabad_Blues_P1_Bridge.Farabad.zip)

#### Описание 
Первая миссия кампании Farabad Blues

**Comment by Comrade333** [comment]
1) Жестко просаживается фпс, повыключай симуляцию врекам и укреплениям, которые не снести.

2) В поддержке указаны только хамви с М2, на старте есть с мк19.

3) значительная разница в магазинах между людьми с гп и без, может для того чтобы ускорить начало миски, раздать гренадерам сразу рюкзаки и добить количество магазинов до 12 как у райфлменов.
 Знаю рюкзаки есть в технике, игроки в любом случае сделают это самостоятельно, но это займет время, плюс избежим ситуации с залутаными машинами для второй волны.

4) 10 SMK, но в настройках их 9)))

Вкусовщина 
очень много одноразовых ПТ средств, не чувствуется особенность СМАВ челивков, все смогут по несколько раз выстрелить с одноразки)))
Конвой может перед мостом или за ним поставить, а то че они там встали

**Comment by Arsdor** [comment]
1) У значительной части декоративных объектов не отключена симуляция.
2) Нет батарей для ЛЦУ
3) У большинства классов всего 7 магазинов. Понятно, что в машинках есть ещё, и там же рюкзаки, но кажется лишним гемором.
4) У ФТЛов нет сигнальных средств
5) У стрелков нет пулемётных лент по умолчанию. С учётом того, что это часто роль для новичков, не стоит оставлять это на их откуп.
6) В описании миссии ошибка - takistan positions вместо takistan_i_ (срав. Pakistan - pakistani)
7) Prison win/arty win - опечатка: "Радачи выполнены"
8) SMAW Gunner - не подцепляется kit. SMAW No. 2 - то же самое
9) Нет сайдармов даже у пулемётчиков. Может звучать как доёбка, но раз уж у нас кампания, где жизни важны™ - оружие последнего шанса будет кстати.

**Comment by OneScheer** [comment]
Comrade:
1. Потыкал
2. Указал
3. Выдал рюкзаки с патронами
4. Исправил на 10
5. Снизил кол-во ПТ средств в машинках до 1
6. Переставил на восточный берег
Arsdor
1. см. выше
2. Зачем батареи для ЛЦУ? (отсылку на generation kill понял), объяснил в дискорде
3. Добавил гренадерам
4. Пересобрал сигнальные средства, выдал побольше СЛу и добавил ФТЛ
5. Выдал две ленты по 200
6. Исправил
7. Исправил
8. Добавил в assignment table
9. сайдарм не нужон, если че возьмут в арсенале я считаю
Кабан
1. Нашел что не зарандомил униформу союзникам, исправил
2.

**Comment by 10Dozen** [comment]
- У пулеметчиков ленты с зеленым трассером, как у врагов.
- При прилете самолетов по десять раз писалось в чятик. Алсо есть крутой модуль Chatter, как раз чтобы выводить переговорчики красиво (может быть)
- АКОГ 6х у пулемета немного смущает, не помню чтобы видел такое ИРЛ, обычно м145 или аког4х
