### ISSUE TITLE
CO16 Western

### ISSUE THREAD

**Issue by OneScheer** [TacticalShift/mmo#50]
#### Миссия:
- [Ссылка_на_файл_архива_миссии](https://github.com/TacticalShift/mmo/blob/main/CO16_Western_1A.dingor.zip)

#### Описание 
Ковбои освобождают городок от бандитов

**Comment by Invaderok** [comment]
1) Спавн ковбоев слишком близко к зоне операции, боты агрятся почти сразу, перемести за холмик или как то закрой нас.
2) Не отключен дозен гир редактор.
3) Ящик в воздухе
![image](https://github.com/user-attachments/assets/902537a2-2cef-429b-a4fb-7b6630db462a)
4) Можно еще добавить вагоны
![image](https://github.com/user-attachments/assets/69542f20-4143-43bd-83e8-a4abd1c2c64d)
5) Я бы зациклил какой то трек в городе в салуне с музыкой из вестерна.
6) Даешь Water TANK и снайпера туда какого-то.
![image](https://github.com/user-attachments/assets/3a377d18-3a44-4160-89d7-cbcfc37d4ce6)

7) Я бы сделал планировку как то поближе в одну улицу, как правило в вестернах идет алея и слева справа от её все дома типо магазины, банки и тд, так как в то время небольшие деревушки такие были как хаб, жили все в основном в своих домах по ебеням, если брать по примеру РДР2.
8) ЖД полотно можно сделать длиннее чтобы в глаза не бросалось что она короткая.
