### ISSUE TITLE
CO27_Operation_Cou_Noue.Farabad

### ISSUE THREAD

**Issue by Comrade333** [TacticalShift/mmo#51]
#### Миссия:
- [Ссылка_на_файл_архива_миссии](https://github.com/TacticalShift/mmo/blob/main/CO27_Operation_Cou_Noue.Farabad.zip)

#### Описание 
Французские силы присоединяются к операции на Фарабаде

**Comment by OneScheer** [comment]
- сделай минам east revealMine this
- передвинь CCP, а то носилки спавнятся в разрушенном доме 
![image](https://github.com/user-attachments/assets/c6f27acb-b647-4686-b65f-7d412fb711a7)
- добавь в аванпост на горе (форт) побольше челиков, я вижу там потенциал охуенной битвы

**Comment by Comrade333** [comment]
1) Добавил
2) Передвинул
3) Увеличил количество на 5 человек
4) Сделал мини кит

**Comment by OneScheer** [comment]
Одобрено
