### ISSUE TITLE
CO15 Webs of Steel 2 

### ISSUE THREAD

**Issue by Invaderok** [TacticalShift/mmo#8]
#### Миссия:
[- Ссылка_на_файл_архива_миссии](https://github.com/TacticalShift/mmo/blob/main/CO15_Webs_of_Steel_2_1A.MCN_Aliabad.7z)

#### Описание 
Second Lebanon War, IDF attacks Hezbollah artillery and searches for a downed allied Apache.

**Comment by OneScheer** [comment]
- В описании миссии строка "123"
- В description.ext сделай пунктуацию в описании задач: "Цели: Уничтожить артилерию, установить**,** что с вертолетом и пилотами"
- Через минуту-две после запуска миссии Аллах с небес посылает пакет града на спавн, так и должно быть?
- Не уверен, что танк будет стрелять через камуфляжную сетку 
![image](https://github.com/TacticalShift/mmo/assets/20025467/4ad7e4f1-5a78-4c3a-be1c-4adbab86a85a)
- Если ты хочешь чтобы на observe point боты стояли в укрепе, сделай через entrenched и AI Building Position
- В брифинге указано про спасение экипажа. Экипажа в миссии нет как в редакторе, так и после запуска. (нашел то что он лежит у стенки, рядом модули dzn_gear с idf_pilot) - они должны быть живые или мертвые? : )
- Униформа M-88 с совецкой звездой, вроде подходит по цвету, но можно посмотреть альтернативы (не требует исправления, просто замечание)

**Comment by Invaderok** [comment]
1. Бля вроде везде убирал 123, но на слоттинге осталось, пересоздал конфиг сценарий.
2. Изменил ext описание, так как запятые там не появляются почему то.
3. Так задумано мишн мейкером, БМ-21 которые нужно уничтожить по миссии произвели атаку по нашим позициям с которых ранее отступила часть взвода попавшая в засаду (но не по респу все безопасно, ну относительно :D), примерно полторы минуты летят снаряды со старта миссии.
4. Танк через сетку стреляет, проверено.
5. Как я бы не пытался, они там не ресаются. (видно бункер не билдинг). По этому оставил все как было.
6. В брифинге указано что их судьба неизвестна. В задачах - узнать что с вертолетом и экипажем. Ну по факту их расстреляли, если спойлерить, вин кондишн миссии в том чтобы взорвать бмки и вернуться к вертолету для их эвакуации тел (зона).
7. Я не знаю где ты звезды увидел там, я облетал всего себя и их не вижу. К сожалению это единственный вариант формы такого цвета, который максимально соответствует ирл прототипам 2006г. Там они конечно посвободнее в рукавах и штанах, но ШОШПОДЕЛОТЬ.

**Comment by Comrade333** [comment]
**Общее**

1. Грады пускай лучше лупят куда-то за территорию операции, но не далеко чтоб игроки слышали, в нынешнем виде могут убить.
2. Думаю с пилотов бы все залутали, а не положили бы рядом с трупами)))
3. Добавь легкий дымок на вертолет, чтоб там 0.15-0.25 от нормы было)

**Техника**

1. Намеры начали поставлять только в 2008, у нас 2006. Как раз опыт второй ливанской и ускорил программу с намерами. Дабы придерживаться выбранного исторического сеттинга лучше дать М113.
2. У композиции FARP замени М113 в вудланде на песочный.


**Киты**

Враги:
1. Просятся обычные вражеские боты только с стрелковкой.
2. Лучше убрать метис у ботов как ПТ, есть ведь статичные. Сложно в ИРЛ с плеча с этой штуки стрелять, а ботам будет легко. Оставь пт срелков с РПГ-7 и добавь еще один кит с одноразкой тип мухи.
3. Можно зарандомить помимо вудланда им еще и марпат, особенно вариации в перемешку (Мои хотелки)

Союзники:

1. Можно добавить м16а2 carabin вместо м4а1, как раз как car 15 будет)) (Мои хотелки)
2. Лучше выдать такую форму, выглядит не сильно новей, но к всему остальному больше подходит. На солнце особенно видно как нынешняя не подходит и звездочки на ремне не будет.

![image](https://github.com/TacticalShift/mmo/assets/38052105/de675e6e-8a58-439a-b5f0-5ad725e717cc)

**Comment by Comrade333** [comment]
для сравнения

![image](https://github.com/TacticalShift/mmo/assets/38052105/6d2348e5-aad0-4405-a177-26f9b9fbfce7)

**Comment by Invaderok** [comment]
Общее:
1. В этом и смысл градов чтобы проатаковать наши "типо прошлые" позиции. Они не убьют, если ты специально не побежишь в первые полторы минуты игры чтобы их словить. Эффекта тряски камеры не будет на спавне если дальше отодвинуть. Я кучу раз сколько не спавнился и бахало, ниразу не было даже ранения. Грады это не ядерная бомба.
2. Так как позиции еще не покинуты, как и машины не уехали, их просто не успели залутать, автоматы забрал, окей это логично, а шлемафоны то зачем им с барахлом ломанным)) 
3. Дыма нет потому что вертолет сбили "вчера" и он уже выгорел, но если прям очень хочеЦЦа, могу добавить если покажешь как.
4. т55 незачем кататься, это пустая трата топлива. Окопал.

Техника:
1. Убрал, добавил м113.
2. ССР м113 поменял на пустынный.

Враги:

1. Добавил кит легкого пеха с трофейными м72лав.
2. Убрал метисы, вместо них просто ПТ РПГ + добавил метисы стационарные для баланса.
3. В 2006 марпата не было у них, они были на иракских бомжей похожих, добавил рандом касок, вестов.

Союзники:

1. Добавил в рандом карабин.
2. Добавил Маг с деревом и без планок.
3. Форму поменял на предложенную. Хотя и в старой не было звезды на поясе. 
![image](https://github.com/TacticalShift/mmo/assets/168902359/6b5592f9-c5bb-449f-a3e3-db4c5ccdc90d)
Так же сменил рацию ДВ на более подходящую по цвету.
4. Актуализировал брифинг после изменений.

**Comment by OneScheer** [comment]
- смари, если ты хочешь чтобы танки были окопаны и никуда не двигались, выдай им только Gunner, иначе уедут
- Сетка на танке так и осталась
![image](https://github.com/TacticalShift/mmo/assets/20025467/afbcb4b2-d481-4de9-9e44-1a97c18765dd)

**Comment by Comrade333** [comment]
Вопросов не имею

**Comment by Invaderok** [comment]
Замена коробок на коробки с трасерами у пулеметчика
Замена авто на м151
Изменение названия слотов у крюменов.

**Comment by OneScheer** [comment]
Всё четко!
