### ISSUE TITLE
CO28 Scimitars Drawn

### ISSUE THREAD

**Issue by OneScheer** [TacticalShift/mmo#9]
#### Миссия:
[Scimitars Drawn
](https://github.com/TacticalShift/mmo/blob/main/CO28_Scimitars_Drawn.DYA.zip)
#### Описание 
Британская тактическая группа штурмует сирийские позиции. Есть бронетехника у союзников и противника, артиллерийская поддержка.

**Comment by Invaderok** [comment]
Я такой себе ревьюер но:
1) ![image](https://github.com/TacticalShift/mmo/assets/168902359/7d46dc16-c82c-4d55-9b00-0c997c8ea0da)
Этот пулик стреляет сквозь кусты, куда смотрит скриншот, если идти с того направления. Если цель держать левый фланг, лучше его ближе к зданию поставить чтобы он не стрелял направо сквозь деревья (игроки охуеют когда по ним будут шмалять неизвестно откуда).

2) АГСы в дырках почему то не стреляли, что по мне, что по моим ботам, возможно это проверить нужно.
3) Цимитары пустые, нет банально даже магазинов, бинтов | ремонтных наборов. Возможно стоит туда дать минимальный какой-то набор снаряжения
4) Зачем в ките kit_uk_r - второй шлем в рюкзаке?
5) Выбивает ошибку there is no kit при старте. (я хз может просто сделать кит пустой для дшкм).
6) А пилоты разве вообще без оружия летают? (кит пилот) По идее у них хотя-бы должны быть пистолеты.

**Comment by OneScheer** [comment]
1. Положил пулик на землю слева
2. В дырках это какие?
3. Засунул медицину и рем. набор
4. Убрал из кита (он и не должен использоваться, нет слота Rifleman)
5. Баг в framework, на работоспособность не влияет
6. Убрал кит пилота

**Comment by 10Dozen** [comment]
> Баг в framework, на работоспособность не влияет
Нет тикета, значит не баг яскозал.

**Comment by OneScheer** [comment]
> Нет тикета, значит не баг яскозал.

https://github.com/10Dozen/dzn_tSFramework/issues/129

**Comment by Home1234Home** [comment]
![image](https://github.com/TacticalShift/mmo/assets/164507439/e9bbb11d-61e8-41f0-a492-1626b96e609b)
В технике на работает прицел, хз может это у меня что-то

**Comment by OneScheer** [comment]
> ![image](https://private-user-images.githubusercontent.com/164507439/329766044-e9bbb11d-61e8-41f0-a492-1626b96e609b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTU5NjcsIm5iZiI6MTcxNTQxNTY2NywicGF0aCI6Ii8xNjQ1MDc0MzkvMzI5NzY2MDQ0LWU5YmJiMTFkLTYxZTgtNDFmMC1hNDkyLTE2MjZiOTZlNjA5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwODIxMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjM4YzVhNTM0M2JkMDc1MWVkMjczZmZjNmM2ZmE4MDE1ZmYyMTQyYTE5YTE4NjQ2N2QyM2MwNzU3MTNjZDAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ld-Ff8nWiAUUavkv2DZflYqK5-nUMxxxbprwZJ4oK8U) В технике на работает прицел, хз может это у меня что-то

Нажми в меню по колёсику "open door"

**Comment by Comrade333** [comment]
**Брифинг**

1. Отсутствует описание миссии в descriptions.
2. Добавь информацию об арте в поддержку.
3. Также в поддержке укажи про основной скимитар, а то там только про резеврный. Я видел что в дружественных силах про него написано, но мы вроде там пишем про количество людей без техники.
4. Джипы бы сразу поставил, чтобы избежать ситуация когда гсо заспаунит не в британской раскраске или с вооружением.


**Kits**

1. LSW gunner весит 25 кг, ходит без трубы. ФТЛ весит 36 кг ходит с трубой.
Бриты так в ИРЛ ходили? может вместо фтла он все же будет носить трубу?
2. Ванильный кит снаряги из Бульдогов специально отсавил? там джавелины (которые сто процентов кто-то возьмет и будет плакать, что он устает каждые 50 метров), рем комплекты, аптечки.
3. У мг и фтл UNIFORM_ITEMS_L.
4. Выдает ошибку there is no kit при старте.


**По теме от Home**

1. Там в прицеле надо "Open door" прожать, все работает.
Добавил бы инфу про это в замечания.

**Comment by OneScheer** [comment]
1. Добавил описание
2. Скопировал строку в поддержку
3. Поставил джипы

1.  Добавил трубу LSW Gunner
2. Кит не ванильный, убрал джавелин
3. У фтл так и должно быть, кит mg это legacy с прошлой миски, убрал
4. Добавил в kit_syr_random несколько kit_syr_at

1. Добавил в замечания

**Comment by Invaderok** [comment]
По моим замечанием все ок, с моей стороны одобрено.

**Comment by Comrade333** [comment]
По моим аналогично, случайно закрыл ветку..
